changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - github-actions[bot]
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: New Features
      labels:
        - feature
    - title: Bug Fixes
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
    - title: Dependencies
      labels:
        - dependencies
    - title: Refactoring
      labels:
        - refactoring

release-prs:
  includeLabels:
    - release

footer: |
  Published by [semantic-release](https://github.com/semantic-release/semantic-release)
