/**
 * Base Data Transfer Object interface with optional ID field
 * Used as a base for all DTOs that may contain an identifier
 */
export interface IDto {
    id?: number | string;
}

/**
 * Data Transfer Object interface for creating new entities
 * Extends IDto but typically the id field should be omitted during creation
 * as it's usually auto-generated by the database
 */
export interface ICreateDto extends IDto {}

/**
 * Data Transfer Object interface for updating existing entities
 * Extends IDto and allows partial updates to entity fields
 */
export interface IUpdateDto extends IDto {}

